+function($){'use strict';var Validator=function(element,options){this.$element=$(element)
this.options=options
this.toggleSubmit()
this.$element.on('input.bs.validator change.bs.validator focusout.bs.validator',$.proxy(this.validateInput,this))
this.$element.find('[data-match]').each(function(){var $this=$(this)
var target=$this.data('match')
$(target).on('input.bs.validator',function(e){$this.val()&&$this.trigger('input')})})}
Validator.DEFAULTS={delay:500,errors:{match:'Does not match',minlength:'Not long enough'}}
Validator.VALIDATORS={native:function($el){var el=$el[0]
return el.checkValidity?el.checkValidity():true},match:function($el){var target=$el.data('match')
return!$el.val()||$el.val()===$(target).val()},minlength:function($el){var minlength=$el.data('minlength')
return!$el.val()||$el.val().length>=minlength}}
Validator.prototype.validateInput=function(e){var $el=$(e.target)
var prevErrors=$el.data('bs.errors')
var errors
this.$element.trigger(e=$.Event('validate.bs.validator',{relatedTarget:$el[0]}))
if(e.isDefaultPrevented())return
$el.data('bs.errors',errors=this.runValidators($el))
errors.length?this.showErrors($el):this.clearErrors($el)
if(!prevErrors||errors.toString()!==prevErrors.toString()){e=errors.length?$.Event('invalid.bs.validator',{relatedTarget:$el[0],detail:errors}):$.Event('valid.bs.validator',{relatedTarget:$el[0],detail:prevErrors})
this.$element.trigger(e)}
this.toggleSubmit()
this.$element.trigger($.Event('validated.bs.validator',{relatedTarget:$el[0]}))}
Validator.prototype.runValidators=function($el){var errors=[]
var validators=[Validator.VALIDATORS.native]
$.each(Validator.VALIDATORS,$.proxy(function(key,validator){if(($el.data(key)||key=='native')&&!validator.call(this,$el)){var error=$el.data(key+'-error')||$el.data('error')||key=='native'&&$el[0].validationMessage||this.options.errors[key]
!~errors.indexOf(error)&&errors.push(error)}},this))
return errors}
Validator.prototype.validate=function(){var delay=this.options.delay
this.options.delay=0
this.$element.find(':input').trigger('input')
this.options.delay=delay
return this}
Validator.prototype.showErrors=function($el){function callback(){var $group=$el.closest('.form-group')
var $block=$group.find('.help-block.with-errors')
var errors=$el.data('bs.errors')
if(!errors.length)return
errors=$('<ul/>').addClass('list-unstyled').append($.map(errors,function(error){return $('<li/>').text(error)}))
$block.data('bs.originalContent')===undefined&&$block.data('bs.originalContent',$block.html())
$block.empty().append(errors)
$group.addClass('has-error')}
if(this.options.delay){window.clearTimeout($el.data('bs.timeout'))
$el.data('bs.timeout',window.setTimeout(callback,this.options.delay))}else callback()}
Validator.prototype.clearErrors=function($el){var $group=$el.closest('.form-group')
var $block=$group.find('.help-block.with-errors')
$block.html($block.data('bs.originalContent'))
$group.removeClass('has-error')}
Validator.prototype.hasErrors=function(){function fieldErrors(){return!!($(this).data('bs.errors')||[]).length}
return!!this.$element.find(':input').filter(fieldErrors).length}
Validator.prototype.isIncomplete=function(){function fieldIncomplete(){return this.type==='checkbox'?!this.checked:this.type==='radio'?!$('[name="'+this.name+'"]:checked').length:$.trim(this.value)===''}
return!!this.$element.find('[required]').filter(fieldIncomplete).length}
Validator.prototype.toggleSubmit=function(){var $btn=this.$element.find(':submit')
$btn.attr('disabled',this.isIncomplete()||this.hasErrors())}
var old=$.fn.validator
$.fn.validator=function(option){return this.each(function(){var $this=$(this)
var options=$.extend({},Validator.DEFAULTS,$this.data(),typeof option=='object'&&option)
var data=$this.data('bs.validator')
if(!data)$this.data('bs.validator',(data=new Validator(this,options)))
if(typeof option=='string')data[option]()})}
$.fn.validator.Constructor=Validator;$.fn.validator.noConflict=function(){$.fn.validator=old
return this}
$(window).on('load',function(){$('form[data-toggle="validator"]').each(function(){var $form=$(this)
$form.validator($form.data())})})}(jQuery);
(function(){var a,b=function(a,b){return function(){return a.apply(b,arguments)}};a=function(){function a(){}
return a.prototype.extend=function(a,b){var c,d;for(c in a)
d=a[c],null!=d&&(b[c]=d);return b},a.prototype.isMobile=function(a){return/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(a)},a}(),this.WOW=function(){function c(a){null==a&&(a={}),this.scrollCallback=b(this.scrollCallback,this),this.scrollHandler=b(this.scrollHandler,this),this.start=b(this.start,this),this.scrolled=!0,this.config=this.util().extend(a,this.defaults)}
return c.prototype.defaults={boxClass:"wow",animateClass:"animated",offset:0,mobile:!0},c.prototype.init=function(){var a;return this.element=window.document.documentElement,"interactive"===(a=document.readyState)||"complete"===a?this.start():document.addEventListener("DOMContentLoaded",this.start)},c.prototype.start=function(){var a,b,c,d;if(this.boxes=this.element.getElementsByClassName(this.config.boxClass),this.boxes.length){if(this.disabled())
return this.resetStyle();for(d=this.boxes,b=0,c=d.length;c>b;b++)
a=d[b],this.applyStyle(a,!0);return window.addEventListener("scroll",this.scrollHandler,!1),window.addEventListener("resize",this.scrollHandler,!1),this.interval=setInterval(this.scrollCallback,50)}},c.prototype.stop=function(){return window.removeEventListener("scroll",this.scrollHandler,!1),window.removeEventListener("resize",this.scrollHandler,!1),null!=this.interval?clearInterval(this.interval):void 0},c.prototype.show=function(a){return this.applyStyle(a),a.className=""+a.className+" "+this.config.animateClass},c.prototype.applyStyle=function(a,b){var c,d,e;return d=a.getAttribute("data-wow-duration"),c=a.getAttribute("data-wow-delay"),e=a.getAttribute("data-wow-iteration"),a.setAttribute("style",this.customStyle(b,d,c,e))},c.prototype.resetStyle=function(){var a,b,c,d,e;for(d=this.boxes,e=[],b=0,c=d.length;c>b;b++)
a=d[b],e.push(a.setAttribute("style","visibility: visible;"));return e},c.prototype.customStyle=function(a,b,c,d){var e;return e=a?"visibility: hidden; -webkit-animation-name: none; -moz-animation-name: none; animation-name: none;":"visibility: visible;",b&&(e+="-webkit-animation-duration: "+b+"; -moz-animation-duration: "+b+"; animation-duration: "+b+";"),c&&(e+="-webkit-animation-delay: "+c+"; -moz-animation-delay: "+c+"; animation-delay: "+c+";"),d&&(e+="-webkit-animation-iteration-count: "+d+"; -moz-animation-iteration-count: "+d+"; animation-iteration-count: "+d+";"),e},c.prototype.scrollHandler=function(){return this.scrolled=!0},c.prototype.scrollCallback=function(){var a;return this.scrolled&&(this.scrolled=!1,this.boxes=function(){var b,c,d,e;for(d=this.boxes,e=[],b=0,c=d.length;c>b;b++)
a=d[b],a&&(this.isVisible(a)?this.show(a):e.push(a));return e}.call(this),!this.boxes.length)?this.stop():void 0},c.prototype.offsetTop=function(a){var b;for(b=a.offsetTop;a=a.offsetParent;)
b+=a.offsetTop;return b},c.prototype.isVisible=function(a){var b,c,d,e,f;return c=a.getAttribute("data-wow-offset")||this.config.offset,f=window.pageYOffset,e=f+this.element.clientHeight-c,d=this.offsetTop(a),b=d+a.clientHeight,e>=d&&b>=f},c.prototype.util=function(){return this._util||(this._util=new a)},c.prototype.disabled=function(){return!this.config.mobile&&this.util().isMobile(navigator.userAgent)},c}()}).call(this);wow=new WOW({animateClass:'animated',mobile:false});wow.init();
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();var Royal_Preloader={_overlay:null,_overlay_bg:null,_loader:null,_name:null,_percentage:null,_on_complete:null,_text_loader:null,_text_loader_overlay:null,_logo_loader:null,_logo_loader_meter:null,_total:0,_loaded:0,_image_queue:[],_percentage_loaded:0,_mode:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._mode?Royal_Preloader._mode:"number"}(),_text:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._text?Royal_Preloader._text:"loading..."}(),_opacity:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._opacity?Royal_Preloader._opacity:1}(),_images:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._images?Royal_Preloader._images:{}}(),_show_info:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._show_info?Royal_Preloader._show_info:!0}(),_show_percentage:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._show_percentage?Royal_Preloader._show_percentage:!0}(),_background:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._background?Royal_Preloader._background:["#000000"]}(),_logo:function(){return"undefined"!==typeof Royal_Preloader&&"undefined"!==typeof Royal_Preloader._logo?Royal_Preloader._logo:"none"}(),_timeout:10,_use_css_animation:!0,_css3SupportDetect:function(){var a=document.body.style;if("string"==typeof a.transition)
return Royal_Preloader._use_css_animation=!0;for(var b=["Webkit","Moz","Khtml","O","ms"],c=0;c<b.length;c++)
if("string"==typeof a[b[c]+"Transition"])
return Royal_Preloader._use_css_animation=!0;return Royal_Preloader._use_css_animation=!1},_init:function(){Royal_Preloader._css3SupportDetect();Royal_Preloader._total=0;$.each(Royal_Preloader._images,function(){Royal_Preloader._total++});Royal_Preloader._build();Royal_Preloader._load()},_build:function(){this._overlay=$("<div>").attr("id","royal_preloader").addClass(this._mode);this._overlay_bg=$("<div>").addClass("background").appendTo(this._overlay).css("background-color",this._background[0]);"number"===this._mode?this._percentage=$("<div>").addClass("percentage").appendTo(this._overlay):"text"===this._mode?(this._text_loader=$("<div>").addClass("loader").text(this._text).appendTo(this._overlay),this._text_loader_overlay=$("<div>").css("background-color",this._background[0]).appendTo(this._text_loader)):(this._logo_loader=$("<div>").css("background-image",'url("'+this._logo+'")').addClass("loader").appendTo(this._overlay),this._logo_loader_meter=$("<div>").css("background-color",this._background[0]).appendTo(this._logo_loader),this._percentage=$("<div>").css("background-color",this._background[0]).addClass("percentage").appendTo(this._overlay),this._show_percentage||this._percentage.hide());1!==this._opacity&&(this._overlay_bg.css("opacity",this._opacity),$(document.body).css("visibility","visible"));this._overlay.appendTo($(document.body));"text"===this._mode&&this._text_loader.css("margin-left",this._text_loader.width()/2*-1)},_load:function(){if("number"===this._mode||"logo"===this._mode)
this._percentage.data("num",0),this._show_percentage&&this._percentage.text("0%");$.each(this._images,function(a,b){var c=function(){Royal_Preloader._imageOnLoad(a,b)},d=new Image;d.onload=c;d.onerror=c;d.src=b});setTimeout(function(){Royal_Preloader._overlay&&Royal_Preloader._animatePercentage(Royal_Preloader._percentage_loaded,100)},1E3*this._timeout)},_animatePercentage:function(a,b){Royal_Preloader._percentage_loaded=a;a<b&&(a++,setTimeout(function(){"number"===Royal_Preloader._mode?Royal_Preloader._show_percentage&&Royal_Preloader._percentage.text(a+"%"):"text"===Royal_Preloader._mode?Royal_Preloader._text_loader_overlay.css("left",a+"%"):(Royal_Preloader._show_percentage&&Royal_Preloader._percentage.text(a+"%"),Royal_Preloader._logo_loader_meter.css("bottom",a+"%"));Royal_Preloader._animatePercentage(a,b)},5),100===a&&Royal_Preloader._loadFinish())},_animateName:function(a,b){if("number"===this._mode){var c=this._name=$("<div>").addClass("name").text(a).appendTo(this._overlay);requestAnimFrame(function(){c.css("transform","rotateZ("+parseInt(60*Math.random()-30)+"deg)")});this._use_css_animation?this._overlay_bg.css("background-color",this._background[this._loaded%this._background.length]):(this._name.css({opacity:1,top:"50%"}),this._name.animate({top:"20%",opacity:0},300),this._overlay_bg.animate({backgroundColor:this._background[this._loaded%this._background.length]},300,"linear"))}
setTimeout(function(){b()},300)},_imageOnLoad:function(a,b){this._image_queue.push({name:a,image_src:b});this._image_queue.length&&this._image_queue[0].image_src===b&&this._processQueue()},_reQueue:function(){Royal_Preloader._image_queue.splice(0,1);Royal_Preloader._processQueue()},_processQueue:function(){0!==this._image_queue.length&&(this._loaded++,Royal_Preloader._animatePercentage(Royal_Preloader._percentage_loaded,parseInt(this._loaded/this._total*100,10)),this._show_info?this._animateName(this._image_queue[0].name,this._reQueue):this._reQueue())},_loadFinish:function(){this._use_css_animation?(this._overlay.addClass("complete"),$(document.body).removeClass("royal_loader")):setTimeout(function(){Royal_Preloader._overlay.addClass("complete");$(document.body).removeClass("royal_loader")},500);this._on_complete&&this._on_complete();setTimeout(function(){Royal_Preloader._overlay.remove();Royal_Preloader._overlay=null},1E3)},config:function(a){"undefined"!==typeof a.mode&&(this._mode=a.mode);"undefined"!==typeof a.text&&(this._text=a.text);"undefined"!==typeof a.timeout&&(this._timeout=parseInt(a.timeout));"undefined"!==typeof a.showPercentage&&(this._show_percentage=a.showPercentage?!0:!1);"undefined"!==typeof a.showInfo&&(this._show_info=a.showInfo?!0:!1);"undefined"!==typeof a.background&&(this._background=a.background);"undefined"!==typeof a.logo&&(this._logo=a.logo);"undefined"!==typeof a.opacity&&(this._opacity=a.opacity);"undefined"!==typeof a.onComplete&&(this._on_complete=a.onComplete);"undefined"!==typeof a.images&&(this._images=a.images,Royal_Preloader._total=0,$.each(this._images,function(a,c){Royal_Preloader._total++}))}};$(document).ready(Royal_Preloader._init);Royal_Preloader.config({mode:'number',timeout:0,showPercentage:true,opacity:1});
(function(jQuery){var jQuerywindow=jQuery(window);var windowHeight=jQuerywindow.height();jQuerywindow.resize(function(){windowHeight=jQuerywindow.height();});jQuery.fn.parallax=function(xpos,speedFactor,outerHeight){var jQuerythis=jQuery(this);var getHeight;var firstTop;var paddingTop=0;jQuerythis.each(function(){firstTop=jQuerythis.offset().top;});if(outerHeight){getHeight=function(jqo){return jqo.outerHeight(true);};}else{getHeight=function(jqo){return jqo.height();};}
if(arguments.length<1||xpos===null)xpos="50%";if(arguments.length<2||speedFactor===null)speedFactor=0.1;if(arguments.length<3||outerHeight===null)outerHeight=true;function update(){var pos=jQuerywindow.scrollTop();jQuerythis.each(function(){var jQueryelement=jQuery(this);var top=jQueryelement.offset().top;var height=getHeight(jQueryelement);if(top+height<pos||top>pos+windowHeight){return;}
jQuerythis.css('backgroundPosition',xpos+" "+Math.round((firstTop-pos)*speedFactor)+"px");});}
jQuerywindow.bind('scroll',update).resize(update);update();};})(jQuery);
;(function(a){if(typeof define==='function'&&define.amd){define(['jquery'],a)}else{a(jQuery)}}(function($){var j=$.scrollTo=function(a,b,c){return $(window).scrollTo(a,b,c)};j.defaults={axis:'xy',duration:parseFloat($.fn.jquery)>=1.3?0:1,limit:true};j.window=function(a){return $(window)._scrollable()};$.fn._scrollable=function(){return this.map(function(){var a=this,isWin=!a.nodeName||$.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!isWin)return a;var b=(a.contentWindow||a).document||a.ownerDocument||a;return/webkit/i.test(navigator.userAgent)||b.compatMode=='BackCompat'?b.body:b.documentElement})};$.fn.scrollTo=function(f,g,h){if(typeof g=='object'){h=g;g=0}if(typeof h=='function')h={onAfter:h};if(f=='max')f=9e9;h=$.extend({},j.defaults,h);g=g||h.duration;h.queue=h.queue&&h.axis.length>1;if(h.queue)g/=2;h.offset=both(h.offset);h.over=both(h.over);return this._scrollable().each(function(){if(f==null)return;var d=this,$elem=$(d),targ=f,toff,attr={},win=$elem.is('html,body');switch(typeof targ){case'number':case'string':if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(targ)){targ=both(targ);break}targ=$(targ,this);if(!targ.length)return;case'object':if(targ.is||targ.style)toff=(targ=$(targ)).offset()}var e=$.isFunction(h.offset)&&h.offset(d,targ)||h.offset;$.each(h.axis.split(''),function(i,a){var b=a=='x'?'Left':'Top',pos=b.toLowerCase(),key='scroll'+b,old=d[key],max=j.max(d,a);if(toff){attr[key]=toff[pos]+(win?0:old-$elem.offset()[pos]);if(h.margin){attr[key]-=parseInt(targ.css('margin'+b))||0;attr[key]-=parseInt(targ.css('border'+b+'Width'))||0}attr[key]+=e[pos]||0;if(h.over[pos])attr[key]+=targ[a=='x'?'width':'height']()*h.over[pos]}else{var c=targ[pos];attr[key]=c.slice&&c.slice(-1)=='%'?parseFloat(c)/100*max:c}if(h.limit&&/^\d+$/.test(attr[key]))attr[key]=attr[key]<=0?0:Math.min(attr[key],max);if(!i&&h.queue){if(old!=attr[key])animate(h.onAfterFirst);delete attr[key]}});animate(h.onAfter);function animate(a){$elem.animate(attr,g,h.easing,a&&function(){a.call(this,targ,h)})}}).end()};j.max=function(a,b){var c=b=='x'?'Width':'Height',scroll='scroll'+c;if(!$(a).is('html,body'))return a[scroll]-$(a)[c.toLowerCase()]();var d='client'+c,html=a.ownerDocument.documentElement,body=a.ownerDocument.body;return Math.max(html[scroll],body[scroll])-Math.min(html[d],body[d])};function both(a){return $.isFunction(a)||typeof a=='object'?a:{top:a,left:a}};return j}));
;(function($,window,document,undefined){var OnePageNav=function(elem,options){this.elem=elem;this.$elem=$(elem);this.options=options;this.metadata=this.$elem.data('plugin-options');this.$win=$(window);this.sections={};this.didScroll=false;this.$doc=$(document);this.docHeight=this.$doc.height();};OnePageNav.prototype={defaults:{navItems:'a',currentClass:'current',changeHash:false,easing:'swing',filter:'',scrollSpeed:750,scrollThreshold:0.5,begin:false,end:false,scrollChange:false},init:function(){this.config=$.extend({},this.defaults,this.options,this.metadata);this.$nav=this.$elem.find(this.config.navItems);if(this.config.filter!==''){this.$nav=this.$nav.filter(this.config.filter);}
this.$nav.on('click.onePageNav',$.proxy(this.handleClick,this));this.getPositions();this.bindInterval();this.$win.on('resize.onePageNav',$.proxy(this.getPositions,this));return this;},adjustNav:function(self,$parent){self.$elem.find('.'+self.config.currentClass).removeClass(self.config.currentClass);$parent.addClass(self.config.currentClass);},bindInterval:function(){var self=this;var docHeight;self.$win.on('scroll.onePageNav',function(){self.didScroll=true;});self.t=setInterval(function(){docHeight=self.$doc.height();if(self.didScroll){self.didScroll=false;self.scrollChange();}
if(docHeight!==self.docHeight){self.docHeight=docHeight;self.getPositions();}},250);},getHash:function($link){return $link.attr('href').split('#')[1];},getPositions:function(){var self=this;var linkHref;var topPos;var $target;self.$nav.each(function(){linkHref=self.getHash($(this));$target=$('#'+linkHref);if($target.length){topPos=$target.offset().top;self.sections[linkHref]=Math.round(topPos);}});},getSection:function(windowPos){var returnValue=null;var windowHeight=Math.round(this.$win.height()*this.config.scrollThreshold);for(var section in this.sections){if((this.sections[section]-windowHeight)<windowPos){returnValue=section;}}
return returnValue;},handleClick:function(e){var self=this;var $link=$(e.currentTarget);var $parent=$link.parent();var newLoc='#'+self.getHash($link);if(!$parent.hasClass(self.config.currentClass)){if(self.config.begin){self.config.begin();}
self.adjustNav(self,$parent);self.unbindInterval();self.scrollTo(newLoc,function(){if(self.config.changeHash){window.location.hash=newLoc;}
self.bindInterval();if(self.config.end){self.config.end();}});}
e.preventDefault();},scrollChange:function(){var windowTop=this.$win.scrollTop();var position=this.getSection(windowTop);var $parent;if(position!==null){$parent=this.$elem.find('a[href$="#'+position+'"]').parent();if(!$parent.hasClass(this.config.currentClass)){this.adjustNav(this,$parent);if(this.config.scrollChange){this.config.scrollChange($parent);}}}},scrollTo:function(target,callback){var offset=$(target).offset().top;$('html, body').animate({scrollTop:offset},this.config.scrollSpeed,this.config.easing,callback);},unbindInterval:function(){clearInterval(this.t);this.$win.unbind('scroll.onePageNav');}};OnePageNav.defaults=OnePageNav.prototype.defaults;$.fn.onePageNav=function(options){return this.each(function(){new OnePageNav(this,options).init();});};})(jQuery,window,document);
(function(t){function e(t){return t.replace(/(:|\.)/g,"\\$1")}var l="1.4.13",o={},s={exclude:[],excludeWithin:[],offset:0,direction:"top",scrollElement:null,scrollTarget:null,beforeScroll:function(){},afterScroll:function(){},easing:"swing",speed:400,autoCoefficent:2,preventDefault:!0},n=function(e){var l=[],o=!1,s=e.dir&&"left"==e.dir?"scrollLeft":"scrollTop";return this.each(function(){if(this!=document&&this!=window){var e=t(this);e[s]()>0?l.push(this):(e[s](1),o=e[s]()>0,o&&l.push(this),e[s](0))}}),l.length||this.each(function(){"BODY"===this.nodeName&&(l=[this])}),"first"===e.el&&l.length>1&&(l=[l[0]]),l};t.fn.extend({scrollable:function(t){var e=n.call(this,{dir:t});return this.pushStack(e)},firstScrollable:function(t){var e=n.call(this,{el:"first",dir:t});return this.pushStack(e)},smoothScroll:function(l,o){if(l=l||{},"options"===l)return o?this.each(function(){var e=t(this),l=t.extend(e.data("ssOpts")||{},o);t(this).data("ssOpts",l)}):this.first().data("ssOpts");var s=t.extend({},t.fn.smoothScroll.defaults,l),n=t.smoothScroll.filterPath(location.pathname);return this.unbind("click.smoothscroll").bind("click.smoothscroll",function(l){var o=this,r=t(this),i=t.extend({},s,r.data("ssOpts")||{}),c=s.exclude,a=i.excludeWithin,f=0,h=0,u=!0,d={},p=location.hostname===o.hostname||!o.hostname,m=i.scrollTarget||(t.smoothScroll.filterPath(o.pathname)||n)===n,S=e(o.hash);if(i.scrollTarget||p&&m&&S){for(;u&&c.length>f;)r.is(e(c[f++]))&&(u=!1);for(;u&&a.length>h;)r.closest(a[h++]).length&&(u=!1)}else u=!1;u&&(i.preventDefault&&l.preventDefault(),t.extend(d,i,{scrollTarget:i.scrollTarget||S,link:o}),t.smoothScroll(d))}),this}}),t.smoothScroll=function(e,l){if("options"===e&&"object"==typeof l)return t.extend(o,l);var s,n,r,i,c=0,a="offset",f="scrollTop",h={},u={};"number"==typeof e?(s=t.extend({link:null},t.fn.smoothScroll.defaults,o),r=e):(s=t.extend({link:null},t.fn.smoothScroll.defaults,e||{},o),s.scrollElement&&(a="position","static"==s.scrollElement.css("position")&&s.scrollElement.css("position","relative"))),f="left"==s.direction?"scrollLeft":f,s.scrollElement?(n=s.scrollElement,/^(?:HTML|BODY)$/.test(n[0].nodeName)||(c=n[f]())):n=t("html, body").firstScrollable(s.direction),s.beforeScroll.call(n,s),r="number"==typeof e?e:l||t(s.scrollTarget)[a]()&&t(s.scrollTarget)[a]()[s.direction]||0,h[f]=r+c+s.offset,i=s.speed,"auto"===i&&(i=h[f]||n.scrollTop(),i/=s.autoCoefficent),u={duration:i,easing:s.easing,complete:function(){s.afterScroll.call(s.link,s)}},s.step&&(u.step=s.step),n.length?n.stop().animate(h,u):s.afterScroll.call(s.link,s)},t.smoothScroll.version=l,t.smoothScroll.filterPath=function(t){return t.replace(/^\//,"").replace(/(?:index|default).[a-zA-Z]{3,4}$/,"").replace(/\/$/,"")},t.fn.smoothScroll.defaults=s})(jQuery);
(function($,window){'$:nomunge';var undefined,aps=Array.prototype.slice,decode=decodeURIComponent,jq_param=$.param,jq_param_fragment,jq_deparam,jq_deparam_fragment,jq_bbq=$.bbq=$.bbq||{},jq_bbq_pushState,jq_bbq_getState,jq_elemUrlAttr,jq_event_special=$.event.special,str_hashchange='hashchange',str_querystring='querystring',str_fragment='fragment',str_elemUrlAttr='elemUrlAttr',str_location='location',str_href='href',str_src='src',re_trim_querystring=/^.*\?|#.*$/g,re_trim_fragment=/^.*\#/,re_no_escape,elemUrlAttr_cache={};function is_string(arg){return typeof arg==='string';};function curry(func){var args=aps.call(arguments,1);return function(){return func.apply(this,args.concat(aps.call(arguments)));};};function get_fragment(url){return url.replace(/^[^#]*#?(.*)$/,'$1');};function get_querystring(url){return url.replace(/(?:^[^?#]*\?([^#]*).*$)?.*/,'$1');};function jq_param_sub(is_fragment,get_func,url,params,merge_mode){var result,qs,matches,url_params,hash;if(params!==undefined){matches=url.match(is_fragment?/^([^#]*)\#?(.*)$/:/^([^#?]*)\??([^#]*)(#?.*)/);hash=matches[3]||'';if(merge_mode===2&&is_string(params)){qs=params.replace(is_fragment?re_trim_fragment:re_trim_querystring,'');}else{url_params=jq_deparam(matches[2]);params=is_string(params)?jq_deparam[is_fragment?str_fragment:str_querystring](params):params;qs=merge_mode===2?params:merge_mode===1?$.extend({},params,url_params):$.extend({},url_params,params);qs=jq_param(qs);if(is_fragment){qs=qs.replace(re_no_escape,decode);}}
result=matches[1]+(is_fragment?'#':qs||!matches[1]?'?':'')+qs+hash;}else{result=get_func(url!==undefined?url:window[str_location][str_href]);}
return result;};jq_param[str_querystring]=curry(jq_param_sub,0,get_querystring);jq_param[str_fragment]=jq_param_fragment=curry(jq_param_sub,1,get_fragment);jq_param_fragment.noEscape=function(chars){chars=chars||'';var arr=$.map(chars.split(''),encodeURIComponent);re_no_escape=new RegExp(arr.join('|'),'g');};jq_param_fragment.noEscape(',/');$.deparam=jq_deparam=function(params,coerce){var obj={},coerce_types={'true':!0,'false':!1,'null':null};$.each(params.replace(/\+/g,' ').split('&'),function(j,v){var param=v.split('='),key=decode(param[0]),val,cur=obj,i=0,keys=key.split(']['),keys_last=keys.length-1;if(/\[/.test(keys[0])&&/\]$/.test(keys[keys_last])){keys[keys_last]=keys[keys_last].replace(/\]$/,'');keys=keys.shift().split('[').concat(keys);keys_last=keys.length-1;}else{keys_last=0;}
if(param.length===2){val=decode(param[1]);if(coerce){val=val&&!isNaN(val)?+val:val==='undefined'?undefined:coerce_types[val]!==undefined?coerce_types[val]:val;}
if(keys_last){for(;i<=keys_last;i++){key=keys[i]===''?cur.length:keys[i];cur=cur[key]=i<keys_last?cur[key]||(keys[i+1]&&isNaN(keys[i+1])?{}:[]):val;}}else{if($.isArray(obj[key])){obj[key].push(val);}else if(obj[key]!==undefined){obj[key]=[obj[key],val];}else{obj[key]=val;}}}else if(key){obj[key]=coerce?undefined:'';}});return obj;};function jq_deparam_sub(is_fragment,url_or_params,coerce){if(url_or_params===undefined||typeof url_or_params==='boolean'){coerce=url_or_params;url_or_params=jq_param[is_fragment?str_fragment:str_querystring]();}else{url_or_params=is_string(url_or_params)?url_or_params.replace(is_fragment?re_trim_fragment:re_trim_querystring,''):url_or_params;}
return jq_deparam(url_or_params,coerce);};jq_deparam[str_querystring]=curry(jq_deparam_sub,0);jq_deparam[str_fragment]=jq_deparam_fragment=curry(jq_deparam_sub,1);$[str_elemUrlAttr]||($[str_elemUrlAttr]=function(obj){return $.extend(elemUrlAttr_cache,obj);})({a:str_href,base:str_href,iframe:str_src,img:str_src,input:str_src,form:'action',link:str_href,script:str_src});jq_elemUrlAttr=$[str_elemUrlAttr];function jq_fn_sub(mode,force_attr,params,merge_mode){if(!is_string(params)&&typeof params!=='object'){merge_mode=params;params=force_attr;force_attr=undefined;}
return this.each(function(){var that=$(this),attr=force_attr||jq_elemUrlAttr()[(this.nodeName||'').toLowerCase()]||'',url=attr&&that.attr(attr)||'';that.attr(attr,jq_param[mode](url,params,merge_mode));});};$.fn[str_querystring]=curry(jq_fn_sub,str_querystring);$.fn[str_fragment]=curry(jq_fn_sub,str_fragment);jq_bbq.pushState=jq_bbq_pushState=function(params,merge_mode){if(is_string(params)&&/^#/.test(params)&&merge_mode===undefined){merge_mode=2;}
var has_args=params!==undefined,url=jq_param_fragment(window[str_location][str_href],has_args?params:{},has_args?merge_mode:2);window[str_location][str_href]=url+(/#/.test(url)?'':'#');};jq_bbq.getState=jq_bbq_getState=function(key,coerce){return key===undefined||typeof key==='boolean'?jq_deparam_fragment(key):jq_deparam_fragment(coerce)[key];};jq_bbq.removeState=function(arr){var state={};if(arr!==undefined){state=jq_bbq_getState();$.each($.isArray(arr)?arr:arguments,function(i,v){delete state[v];});}
jq_bbq_pushState(state,2);};jq_event_special[str_hashchange]=$.extend(jq_event_special[str_hashchange],{add:function(handleObj){var old_handler;function new_handler(e){var hash=e[str_fragment]=jq_param_fragment();e.getState=function(key,coerce){return key===undefined||typeof key==='boolean'?jq_deparam(hash,key):jq_deparam(hash,coerce)[key];};old_handler.apply(this,arguments);};if($.isFunction(handleObj)){old_handler=handleObj;return new_handler;}else{old_handler=handleObj.handler;handleObj.handler=new_handler;}}});})(jQuery,this);(function($,window,undefined){'$:nomunge';var fake_onhashchange,jq_event_special=$.event.special,str_location='location',str_hashchange='hashchange',str_href='href',browser=$.browser,mode=document.documentMode,is_old_ie=browser.msie&&(mode===undefined||mode<8),supports_onhashchange='on'+str_hashchange in window&&!is_old_ie;function get_fragment(url){url=url||window[str_location][str_href];return url.replace(/^[^#]*#?(.*)$/,'$1');};$[str_hashchange+'Delay']=100;jq_event_special[str_hashchange]=$.extend(jq_event_special[str_hashchange],{setup:function(){if(supports_onhashchange){return false;}
$(fake_onhashchange.start);},teardown:function(){if(supports_onhashchange){return false;}
$(fake_onhashchange.stop);}});fake_onhashchange=(function(){var self={},timeout_id,iframe,set_history,get_history;function init(){set_history=get_history=function(val){return val;};if(is_old_ie){iframe=$('<iframe src="javascript:0"/>').hide().insertAfter('body')[0].contentWindow;get_history=function(){return get_fragment(iframe.document[str_location][str_href]);};set_history=function(hash,history_hash){if(hash!==history_hash){var doc=iframe.document;doc.open().close();doc[str_location].hash='#'+hash;}};set_history(get_fragment());}};self.start=function(){if(timeout_id){return;}
var last_hash=get_fragment();set_history||init();(function loopy(){var hash=get_fragment(),history_hash=get_history(last_hash);if(hash!==last_hash){set_history(last_hash=hash,history_hash);$(window).trigger(str_hashchange);}else if(history_hash!==last_hash){window[str_location][str_href]=window[str_location][str_href].replace(/#.*/,'')+'#'+history_hash;}
timeout_id=setTimeout(loopy,$[str_hashchange+'Delay']);})();};self.stop=function(){if(!iframe){timeout_id&&clearTimeout(timeout_id);timeout_id=0;}};return self;})();})(jQuery,this);